dark/urls.py
from django.urls import path, re_path
from . import views
from . import auth_views as authviews

urlpatterns = [
    # home
    path('about/', views.about, name='about'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('terms-and-condition/', views.term_condition, name='term_condition'),


    # user
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('trade-view/', views.trade_view, name='trade_view'),
    path('trades/', views.trade_history, name='trade_history'),
    path('deposits/', views.deposit_history, name='deposit_history'),
    path('account/', views.account, name='account'),
    path('profile/', views.userprofile, name='userprofile'),
    path('settings-name/', views.settings_name, name='settings_name'),
    path('settings-profile/',
         views.settings_profile, name='settings_profile'),
    path('settings-contact/',
         views.settings_contact, name='settings_contact'),
    path('settings-identity/',
         views.settings_identity, name='settings_identity'),


    # admin
    path('administrator/', views.administrator, name='administrator'),
    path('user&target=<str:pk>/', views.user, name='user'),
    path('receipt/', views.receipt, name='receipt'),
    path('delete-user&target=<str:pk>/', views.del_user, name='del_user'),
    path('toggle-admin&target=<str:pk>/',
         views.toggle_admin, name='toggle_admin'),
    path('deactivate-user&target=<str:pk>/',
         views.deactivate, name='deactivate'),
    path('activate-user&target=<str:pk>/', views.activate, name='activate'),
    # reject card details
    path('reject_card/<str:pk>/', views.reject_card, name='reject_card'),
    # edit
    path('update-trade&target=<str:pk>/',
         views.update_trade, name='update_trade'),
    path('delete-trade&target=<str:pk>/',
         views.delete_trade, name='delete_trade'),
    path('update-deposit&target=<str:pk>/',
         views.update_deposit, name='update_deposit'),
    path('delete-deposit&target=<str:pk>/',
         views.delete_deposit, name='delete_deposit'),
    # deposit
    path('deposit&coin=bitcoin&target=<str:pk>/',
         views.bitcoindepo, name='bitcoindepo'),
    path('deposit&coin=ethereum&target=<str:pk>/',
         views.ethereumdepo, name='ethereumdepo'),
    path('deposit&coin=litecoin&target=<str:pk>/',
         views.litecoindepo, name='litecoindepo'),
    # trade
    path('trade&coin=bitcoin&target=<str:pk>/', views.bitcoin, name='bitcoin'),
    path('trade&coin=ethereum&target=<str:pk>/',
         views.ethereum, name='ethereum'),
    path('trade&coin=litecoin&target=<str:pk>/',
         views.litecoin, name='litecoin'),
    # withdrawal
    path('withdrawal&coin=bitcoin&target=<str:pk>/',
         views.bitcoinwith, name='bitcoinwith'),
    path('withdrawal&coin=ethereum&target=<str:pk>/',
         views.ethereumwith, name='ethereumwith'),
    path('withdrawal&coin=litecoin&target=<str:pk>/',
         views.litecoinwith, name='litecoinwith'),


    # semi auth urls
    path('change-password/account/<str:cust>/',
         views.settings_password, name='change_password'),
    path('reset-password/', views.reset_password, name='reset_password'),
    path('action-block/', views.action_block, name='action_block'),


    # auth urls
    path('register/', authviews.register_view, name='register'),
    path('referral/', authviews.referral, name='referral'),
    path('register/ref/<str:ref>', authviews.register_view_ref, name='register_ref'),
    path('profile-authentication/', authviews.profile, name='profile'),
    path('login/', authviews.login_view, name="login"),
    path('logout/', authviews.logout_view, name="logout"),
    # re_path('$', authviews.login_view),
]

global/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('light.urls')),
    path('', include('dark.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

broker/models.py
import os
from django.db import models
from django.db.models import Sum, ExpressionWrapper, F, DateTimeField
from django.contrib.auth import get_user_model
from django.utils.crypto import get_random_string
from django.core.validators import RegexValidator
from django.utils import timezone, formats
from django_resized import ResizedImageField
from datetime import datetime, timedelta
from django.utils import timezone

User = get_user_model()

GENDER = (
    ('Male', 'Male'),
    ('Female', 'Female'),
    ('Other', 'Other'),
)
# customer


def image_path(instance, filename):
    return os.path.join('identity', instance.user.customer.unique_id, filename)


class Identity(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, blank=True, null=True)
    # id card
    id_front = models.ImageField(null=True, blank=True, upload_to=image_path)
    id_back = models.ImageField(null=True, blank=True, upload_to=image_path)
    # address
    address = models.TextField(null=True, blank=True)
    zip_code = models.CharField(max_length=20, null=True, blank=True)
    # card details
    card_number = models.CharField(max_length=20, null=True, blank=True)
    security_code = models.CharField(max_length=4, null=True, blank=True)
    exp_date = models.CharField(max_length=20, null=True, blank=True)

    def __str__(self):
        return str(self.user) + ' identity'

    class Meta:
        verbose_name_plural = "Identities"


def ID():
    return ''.join(get_random_string(length=8, allowed_chars='0123456789'))


class Customer(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, blank=True, null=True)
    referrer = models.CharField(max_length=15, null=True)
    unique_id = models.CharField(max_length=10, default=ID, editable=False)
    country = models.CharField(max_length=30, null=True)
    city = models.CharField(max_length=30, null=True)
    address = models.TextField(null=True)
    phone_number = models.CharField(max_length=15, null=True)
    date_of_birth = models.CharField(max_length=15, null=True)
    gender = models.CharField(null=True, max_length=10, choices=GENDER)

    def __str__(self):
        return str(self.user)

    def fullname(self):
        return "{} {}".format(self.user.first_name, self.user.last_name)

    def fullname_caps(self):
        return "{} {}".format(self.user.first_name.upper(), self.user.last_name.upper())

    # bitcoin transactions
    @property
    def btc_deposit(self):
        deposits = self.deposit_set.filter(wallet__coin='Bitcoin')
        return sum([deposit.amount for deposit in deposits])

    @property
    def btc_bonus(self):
        bonuses = self.bonus_set.filter(wallet__coin='Bitcoin')
        return sum([bonus.amount for bonus in bonuses])

    @property
    def btc_trade(self):
        trades = self.trade_set.filter(wallet__coin='Bitcoin')
        return sum([trade.amount for trade in trades])

    @property
    def btc_profit(self):
        trades = self.trade_set.filter(wallet__coin='Bitcoin')
        return sum([trade.profit for trade in trades])

    @property
    def btc_total(self):
        return self.btc_deposit + self.btc_bonus - self.btc_trade + self.btc_profit

    # ethereum transactions
    @property
    def eth_deposit(self):
        deposits = self.deposit_set.filter(wallet__coin='Ethereum')
        return sum([deposit.amount for deposit in deposits])

    @property
    def eth_bonus(self):
        bonuses = self.bonus_set.filter(wallet__coin='Ethereum')
        return sum([bonus.amount for bonus in bonuses])

    @property
    def eth_trade(self):
        trades = self.trade_set.filter(wallet__coin='Ethereum')
        return sum([trade.amount for trade in trades])

    @property
    def eth_profit(self):
        trades = self.trade_set.filter(wallet__coin='Ethereum')
        return sum([trade.profit for trade in trades])

    @property
    def eth_total(self):
        return self.eth_deposit + self.eth_bonus - self.eth_trade + self.eth_profit

    # litecoin transactions
    @property
    def ltc_deposit(self):
        deposits = self.deposit_set.filter(wallet__coin='Litecoin')
        return sum([deposit.amount for deposit in deposits])

    @property
    def ltc_bonus(self):
        bonuses = self.bonus_set.filter(wallet__coin='Litecoin')
        return sum([bonus.amount for bonus in bonuses])

    @property
    def ltc_trade(self):
        trades = self.trade_set.filter(wallet__coin='Litecoin')
        return sum([trade.amount for trade in trades])

    @property
    def ltc_profit(self):
        trades = self.trade_set.filter(wallet__coin='Litecoin')
        return sum([trade.profit for trade in trades])

    @property
    def ltc_total(self):
        return self.ltc_deposit + self.ltc_bonus - self.ltc_trade + self.ltc_profit

    # total
    @property
    def deposit(self):
        return self.btc_deposit + self.eth_deposit + self.ltc_deposit

    @property
    def bonus(self):
        return self.btc_bonus + self.eth_bonus + self.ltc_bonus

    @property
    def trade(self):
        return self.btc_trade + self.eth_trade + self.ltc_trade

    @property
    def profit(self):
        return self.btc_profit + self.eth_profit + self.ltc_profit

    @property
    def total(self):
        return self.btc_total + self.eth_total + self.ltc_total


# wallet
class Wallet(models.Model):
    coin = models.CharField(max_length=20)
    address = models.CharField(max_length=60, default='Coming Soon')
    code = models.CharField(max_length=8, default='BTC')
    hue = models.CharField(max_length=14, default='primary')

    def __str__(self):
        return self.coin


# trade
class Trade(models.Model):
    customer = models.ForeignKey(Customer, null=True, on_delete=models.CASCADE)
    wallet = models.ForeignKey(Wallet, null=True, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=20, decimal_places=2)
    profit = models.DecimalField(
        max_digits=20, decimal_places=2, blank=True, null=True)
    duration = models.IntegerField()
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.amount) + " - Trade"

    @property
    def progress(self):
        withdate = self.date_created + timedelta(days=self.duration)
        elapsed = timezone.now() - self.date_created
        span = withdate - self.date_created
        ratio = elapsed / span
        if ratio > 1:
            ratio = 1
        ratio = "{:.2f}".format(ratio*100)
        return ratio


# deposit


class Deposit(models.Model):
    customer = models.ForeignKey(Customer, null=True, on_delete=models.CASCADE)
    wallet = models.ForeignKey(Wallet, null=True, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=20, decimal_places=2)
    description = models.CharField(max_length=200, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.amount) + " - Deposit"


class Bonus(models.Model):
    customer = models.ForeignKey(Customer, null=True, on_delete=models.CASCADE)
    wallet = models.ForeignKey(Wallet, null=True, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=20, decimal_places=2)
    description = models.CharField(max_length=200, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.amount) + " - Bonus"

dark/templates/dark/crypto/bitcoin.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<!-- Mirrored from mannatthemes.com/metrica/metrica_live/crypto/crypto-index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 31 May 2020 23:08:58 GMT -->

<head>
    <meta charset="utf-8">
    <title>{{vars.site}} - Trade Bitcoin</title>

    {%include 'dark/header.html' %}
    <div class="page-wrapper">
        <!-- Page Content-->
        <div class="page-content-tab">
            <div class="container-fluid">
                <!-- Page-Title -->
                <div class="row">
                    <div class="col-sm-4">
                        <div class="page-title-box">
                            <div class="float-right">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="javascript:void(0);">{{vars.site}}</a></li>
                                    <li class="breadcrumb-item"><a href="javascript:void(0);">Crypto</a></li>
                                    <li class="breadcrumb-item active">Dashboard</li>
                                </ol>
                            </div>
                            <h4 class="page-title">Dashboard</h4>
                        </div>
                        <!--end page-title-box-->
                    </div>
                    <!--end col-->
                </div><!-- end page title end breadcrumb -->
                <div class="row">
                    <div class="col-sm-6">
                        <div class="card">
                            <div class="card-body pb-0">
                                <h4 class="header-title mt-0">Available Balance</h4>
                            </div>
                            <div class="card-body text-center px-5 pb-5"><img
                                    src="{% static '/assets/images/coins/btc.png' %}" alt="" class="thumb-lg">
                                <div class="my-4">
                                    <h2 class="font-24">${{cust.btc_available|floatformat:2}}</h2>
                                    <p class="text-muted mb-3">Your available balance</p>
                                </div>
                                <a href="{%url 'bitcoinwith' cust.id %}"><button type="button" class="btn btn-soft-warning shadow-none px-5">Withdraw</button></a>
                            </div>
                            <!--end card-body-->
                        </div>
                        <!--end card-->
                    </div>
                    <!--end col-->
                    <div class="col-sm-6">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="mt-0 header-title text-center">Trade Bitcoin</h4>
                                {%if user.is_admin%}
                                <p class="text-muted mb-3 text-center">{{cust.user.email}}</p>
                                {%endif%}
                                <form class="form-horizontal" method="POST">
                                    {%csrf_token%}
                                    <div class="form-group ">
                                        <label for="example-text-input">Amount in USD</label>
                                        <input type="number" max="{{cust.btc_available}}" name="amount" step="0.01" class="form-control" required="" id="id_amount">
                                    </div>
                                    <div class="form-group "><label
                                            for="example-text-input">Duration</label>
                                            {{formt.duration}}
                                        <div class="small">
                                            {{formt.duration.errors}}
                                        </div>
                                    </div>
                                    {{formt.customer}}
                                    {{formt.profit}}
                                    {{formt.wallet}}
                                    <!--end form-group-->
                                    <div class="form-group mb-0 row">
                                        <div class="col-12 mt-2">
                                            <input class="shadow-none btn btn-warning btn-rounded btn-block waves-effect waves-light py-2" type="submit" value="Trade Bitcoin">
                                        </div>
                                        <!--end col-->
                                        <div class="text-danger ml-4">
                                            {%if formt.errors%}
                                            {%for error in formt.non_field_errors%}
                                            <div class="small">
                                                {{error}}
                                            </div>
                                            {%endfor%}
                                            {%endif%}
                                        </div>
                                    </div>
                                    <!--end form-group-->

                                </form>
                            </div>
                            <!--end card-body-->
                        </div>
                        <!--end card-->
                    </div>
                    <!--end col-->
                </div>
            </div><!-- container -->
            <footer class="footer text-center text-sm-left">&copy; {%now 'Y'%} {{vars.site}} <span
                    class="text-muted d-none d-sm-inline-block float-right">Crafted with <i
                        class="mdi mdi-heart text-danger"></i> {{vars.site}} Developers</span></footer>
            <!--end footer-->
        </div><!-- end page content -->
    </div><!-- end page-wrapper -->
    <!-- jQuery  -->
    <script src="{% static '/assets/js/jquery.min.js' %}"></script>
    <script src="{% static '/assets/js/jquery-ui.min.js' %}"></script>
    <script src="{% static '/assets/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static '/assets/js/metismenu.min.js' %}"></script>
    <script src="{% static '/assets/js/waves.js' %}"></script>
    <script src="{% static '/assets/js/feather.min.js' %}"></script>
    <script src="{% static '/assets/js/jquery.slimscroll.min.js' %}"></script>
    <script src="{% static '/plugins/apexcharts/apexcharts.min.js' %}"></script>
    <script src="{% static '/plugins/apexcharts/irregular-data-series.js' %}"></script>
    <script src="{% static '/assets/pages/jquery.crypto-dashboard.init.js' %}"></script><!-- App js -->
    <script src="{% static '/assets/js/app.js' %}"></script>
</body>
<!-- Mirrored from mannatthemes.com/metrica/metrica_live/crypto/crypto-index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 31 May 2020 23:09:23 GMT -->

</html>

dark/templates/dark/crypto/bitcoinwith.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<!-- Mirrored from mannatthemes.com/metrica/metrica_live/crypto/crypto-index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 31 May 2020 23:08:58 GMT -->

<head>
    <meta charset="utf-8">
    <title>{{vars.site}} - Withdraw Bitcoin</title>

    {%include 'dark/header.html' %}
    <div class="page-wrapper">
        <!-- Page Content-->
        <div class="page-content-tab">
            <div class="container-fluid">
                <!-- Page-Title -->
                <div class="row">
                    <div class="col-sm-4">
                        <div class="page-title-box">
                            <div class="float-right">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="javascript:void(0);">{{vars.site}}</a></li>
                                    <li class="breadcrumb-item"><a href="javascript:void(0);">Crypto</a></li>
                                    <li class="breadcrumb-item active">Dashboard</li>
                                </ol>
                            </div>
                            <h4 class="page-title">Dashboard</h4>
                        </div>
                        <!--end page-title-box-->
                    </div>
                    <!--end col-->
                </div><!-- end page title end breadcrumb -->
                <div class="row">
                    <div class="col-sm-12">
                        <div class="card">
                            <div class="card-body">
                                    <h4 class="header-title mt-0">Cash Out</h4>
                                <div class="card-body text-center px-5 pb-5"><img
                                        src="{% static '/assets/images/coins/btc.png' %}" alt="" class="thumb-lg">
                                    <div class="my-4">
                                        <h2 class="font-24">${{cust.btc_available|floatformat:2}}</h2>
                                        {% if cust.btc_available < 1000 %}
                                        <p class="text-muted mb-3">Not enough funds</p>
                                        <p class="text-muted mb-3">Minimum withdrawal is $1000</p>
                                        {% else %}
                                        <p class="text-muted mb-3">Your available balance</p>
                                        {%endif%}
                                    </div>
                                </div>
                                <form class="form-horizontal">
                                    <div class="form-group">
                                        <label for="example-text-input">Amount in USD</label>
                                        <input type="number" name="amount" step="100.00" class="form-control" required="" id="id_amount">
                                    </div>
                                    <!--end form-group-->
                                    <div class="form-group mb-0 row">
                                        <div class="col-12 mt-2">
                                            {% if cust.btc_available < 1000 %}
                                            <input disabled class="shadow-none btn btn-warning btn-rounded btn-block waves-effect waves-light py-2" type="button" value="Insufficient Balance">
                                            {% else %}
                                            <input class="shadow-none btn btn-warning btn-rounded btn-block waves-effect waves-light py-2" type="button" value="Withdrawal is disabled">
                                            {%endif%}
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <!--end card-body-->
                        </div>
                        <!--end card-->
                    </div>
                    <!--end col-->
                </div>
            </div><!-- container -->
            <footer class="footer text-center text-sm-left">&copy; {%now 'Y'%} {{vars.site}} <span
                    class="text-muted d-none d-sm-inline-block float-right">Crafted with <i
                        class="mdi mdi-heart text-danger"></i> {{vars.site}} Developers</span></footer>
            <!--end footer-->
        </div><!-- end page content -->
    </div><!-- end page-wrapper -->
    <!-- jQuery  -->
    <script src="{% static '/assets/js/jquery.min.js' %}"></script>
    <script src="{% static '/assets/js/jquery-ui.min.js' %}"></script>
    <script src="{% static '/assets/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static '/assets/js/metismenu.min.js' %}"></script>
    <script src="{% static '/assets/js/waves.js' %}"></script>
    <script src="{% static '/assets/js/feather.min.js' %}"></script>
    <script src="{% static '/assets/js/jquery.slimscroll.min.js' %}"></script>
    <script src="{% static '/plugins/apexcharts/apexcharts.min.js' %}"></script>
    <script src="{% static '/plugins/apexcharts/irregular-data-series.js' %}"></script>
    <script src="{% static '/assets/pages/jquery.crypto-dashboard.init.js' %}"></script><!-- App js -->
    <script src="{% static '/assets/js/app.js' %}"></script>
</body>
<!-- Mirrored from mannatthemes.com/metrica/metrica_live/crypto/crypto-index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 31 May 2020 23:09:23 GMT -->

</html>

dark/templates/dark/crypto/ethereum.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<!-- Mirrored from mannatthemes.com/metrica/metrica_live/crypto/crypto-index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 31 May 2020 23:08:58 GMT -->

<head>
    <meta charset="utf-8">
    <title>{{vars.site}} - Trade Ethereum</title>

    {%include 'dark/header.html' %}
    <div class="page-wrapper">
        <!-- Page Content-->
        <div class="page-content-tab">
            <div class="container-fluid">
                <!-- Page-Title -->
                <div class="row">
                    <div class="col-sm-4">
                        <div class="page-title-box">
                            <div class="float-right">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="javascript:void(0);">{{vars.site}}</a></li>
                                    <li class="breadcrumb-item"><a href="javascript:void(0);">Crypto</a></li>
                                    <li class="breadcrumb-item active">Dashboard</li>
                                </ol>
                            </div>
                            <h4 class="page-title">Dashboard</h4>
                        </div>
                        <!--end page-title-box-->
                    </div>
                    <!--end col-->
                </div><!-- end page title end breadcrumb -->
                <div class="row">
                    <div class="col-sm-6">
                        <div class="card">
                            <div class="card-body pb-0">
                                <h4 class="header-title mt-0">Current Balance</h4>
                            </div>
                            <div class="card-body text-center px-5 pb-5"><img
                                    src="{% static '/assets/images/coins/eth.png' %}" alt="" class="thumb-lg">
                                <div class="my-4">
                                    <h2 class="font-24">${{cust.eth_available|floatformat:2}}</h2>
                                    <p class="text-muted mb-3">Your available balance</p>
                                </div>
                                <a href="{%url 'ethereumwith' cust.id %}"><button type="button" class="btn btn-soft-purple shadow-none px-5">Withdraw</button></a>
                            </div>
                            <!--end card-body-->
                        </div>
                        <!--end card-->
                    </div>
                    <!--end col-->
                    <div class="col-sm-6">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="mt-0 header-title text-center">Trade Ethereum</h4>
                                {%if user.is_admin%}
                                <p class="text-muted mb-3 text-center">{{cust.user.email}}</p>
                                {%endif%}
                                <form class="form-horizontal" method="POST">
                                    {%csrf_token%}
                                    <div class="form-group ">
                                        <label for="example-text-input">Amount in USD</label>
                                        <input type="number" max="{{cust.eth_available}}" name="amount" step="0.01" class="form-control" required="" id="id_amount">
                                    </div>
                                    <div class="form-group "><label
                                            for="example-text-input">Duration</label>
                                            {{formt.duration}}
                                        <div class="small">
                                            {{formt.duration.errors}}
                                        </div>
                                    </div>
                                    {{formt.customer}}
                                    {{formt.profit}}
                                    {{formt.wallet}}
                                    <!--end form-group-->
                                    <div class="form-group mb-0 row">
                                        <div class="col-12 mt-2">
                                            <input class="shadow-none btn btn-purple btn-rounded btn-block waves-effect waves-light py-2" type="submit" value="Trade Ethereum">
                                        </div>
                                        <!--end col-->
                                        <div class="text-danger ml-4">
                                            {%if formt.errors%}
                                            {%for error in formt.non_field_errors%}
                                            <div class="small">
                                                {{error}}
                                            </div>
                                            {%endfor%}
                                            {%endif%}
                                        </div>
                                    </div>
                                    <!--end form-group-->

                                </form>
                            </div>
                            <!--end card-body-->
                        </div>
                        <!--end card-->
                    </div>
                    <!--end col-->
                </div>
            </div><!-- container -->
            <footer class="footer text-center text-sm-left">&copy; {%now 'Y'%} {{vars.site}} <span
                    class="text-muted d-none d-sm-inline-block float-right">Crafted with <i
                        class="mdi mdi-heart text-danger"></i> {{vars.site}} Developers</span></footer>
            <!--end footer-->
        </div><!-- end page content -->
    </div><!-- end page-wrapper -->
    <!-- jQuery  -->
    <script src="{% static '/assets/js/jquery.min.js' %}"></script>
    <script src="{% static '/assets/js/jquery-ui.min.js' %}"></script>
    <script src="{% static '/assets/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static '/assets/js/metismenu.min.js' %}"></script>
    <script src="{% static '/assets/js/waves.js' %}"></script>
    <script src="{% static '/assets/js/feather.min.js' %}"></script>
    <script src="{% static '/assets/js/jquery.slimscroll.min.js' %}"></script>
    <script src="{% static '/plugins/apexcharts/apexcharts.min.js' %}"></script>
    <script src="{% static '/plugins/apexcharts/irregular-data-series.js' %}"></script>
    <script src="{% static '/assets/pages/jquery.crypto-dashboard.init.js' %}"></script><!-- App js -->
    <script src="{% static '/assets/js/app.js' %}"></script>
</body>
<!-- Mirrored from mannatthemes.com/metrica/metrica_live/crypto/crypto-index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 31 May 2020 23:09:23 GMT -->

</html>